### ISSUE TITLE
Could not get unknown property 'android' for project ':flu_console' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by Baichenghui** [zhujiaming/flu_console#4]
how to resolve

**Comment by yousefak007** [comment]
fork this project or just go to the library folder and go to gradle file in android folder , then follow the image

![image](https://github.com/user-attachments/assets/ca71b19d-de92-47ab-9810-e926583347cd)

**Comment by zhujiaming** [comment]
pull lasted

**Comment by YousefAK009** [comment]
?
